# BakedBean3D — Fusion 360 Master Parameters Import Script v5
# Reads from BakedBean3D_MasterParams_params.csv (generated by convert_xlsx.py)
#
# HOW TO USE:
#   1. Run convert_xlsx.py first to generate/update the CSV from the xlsx
#   2. Open your _MasterParams_FDM.f3d in Fusion 360
#   3. Tools → Add-Ins → Scripts and Add-Ins → [+] → select this file
#   4. Select BakedBean3D_MasterParams → Run
#   5. All parameters created and starred as Favorites automatically
#   6. Insert → Derive in any new design → check Favorites → OK

import adsk.core
import adsk.fusion
import csv
import os
import traceback


def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface
        design = adsk.fusion.Design.cast(app.activeProduct)

        if not design:
            ui.messageBox("No active Fusion 360 design. Open a design file first.")
            return

        csv_path = os.path.join(os.path.dirname(__file__), "BakedBean3D_MasterParams_params.csv")
        if not os.path.exists(csv_path):
            ui.messageBox(
                f"CSV not found:\n{csv_path}\n\n"
                "Run convert_xlsx.py first to generate it from the xlsx."
            )
            return

        rows = []
        with open(csv_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                name = row.get("Name", "").strip()
                expression = row.get("Expression", "").strip()
                unit = row.get("Unit", "").strip()
                comment = row.get("Comment", "").strip()

                if not name or not expression:
                    continue

                rows.append((name, expression, unit, comment))

        if not rows:
            ui.messageBox("CSV is empty or has no valid rows.")
            return

        errors = validate(rows)
        if errors:
            msg = f"{len(errors)} validation error(s):\n\n"
            msg += "\n".join(errors[:20])
            if len(errors) > 20:
                msg += f"\n... and {len(errors) - 20} more"
            ui.messageBox(msg, "Validation Failed")
            return

        ui.messageBox(
            f"BakedBean3D Master Parameters Import v5\n\n"
            f"About to create/update {len(rows)} parameters.\n\n"
            f"Click OK to begin.",
            "Import Parameters",
        )

        params = design.userParameters
        created = 0
        updated = 0
        failed = []

        for name, expression, unit, comment in rows:
            existing = params.itemByName(name)
            if existing:
                try:
                    existing.expression = expression
                    existing.comment = comment
                    existing.isFavorite = True
                    updated += 1
                except Exception as e:
                    failed.append(f"{name}: {e}")
            else:
                try:
                    p = params.add(
                        name,
                        adsk.core.ValueInput.createByString(expression),
                        unit,
                        comment,
                    )
                    p.isFavorite = True
                    created += 1
                except Exception as e:
                    failed.append(f"{name}: {e}")

        msg = (
            f"Import complete!\n\n"
            f"  Created : {created}\n"
            f"  Updated : {updated}\n"
            f"  Failed  : {len(failed)}\n"
        )
        if failed:
            msg += "\nFailures:\n" + "\n".join(failed[:20])
            if len(failed) > 20:
                msg += f"\n... and {len(failed) - 20} more"
        msg += (
            "\n\nNext steps:\n"
            "  1. Modify → Change Parameters to review\n"
            "  2. Save as _MasterParams_FDM.f3d\n"
            "  3. Insert → Derive into new designs → check Favorites"
        )
        ui.messageBox(msg, "BakedBean3D Parameters v5")

    except Exception:
        if ui:
            ui.messageBox(f"Script error:\n{traceback.format_exc()}")


def validate(rows):
    """Validate CSV data before importing into Fusion."""
    errors = []
    seen = {}
    all_names = {r[0] for r in rows}

    for i, (name, expression, unit, comment) in enumerate(rows, 1):
        if name in seen:
            errors.append(f"Row {i}: duplicate param '{name}' (first at row {seen[name]})")
        seen[name] = i

        deps = _extract_deps(expression)
        missing = deps - all_names
        if missing:
            errors.append(f"Row {i}: '{name}' references undefined params: {', '.join(sorted(missing))}")

        preceding = {r[0] for r in rows[:i - 1]}
        unmet = (deps & all_names) - preceding
        if unmet:
            errors.append(f"Row {i}: '{name}' appears before its dependencies: {', '.join(sorted(unmet))}")

    return errors


def _extract_deps(expression):
    """Extract param name references from an expression, ignoring unit suffixes."""
    import re
    tokens = set(re.findall(r"[a-z][a-z0-9_]{2,}", expression))
    return tokens - {"mm", "cm", "deg", "rad"}
